name: Main workflow
on:
  pull_request:
    paths-ignore:
      - "**.adoc"
  push:
    paths-ignore:
      - "**.adoc"
  schedule:
    - cron: 0 0 * * 5
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run ShellCheck
        run: shellcheck bin/*
#  format:
#    runs-on: macos-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Install shfmt
#        run: brew install shfmt
#      - name: Run shfmt
#        run: shfmt -ci -i 2 -d .
  plugin_test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: neovide --version 
        env:
          GITHUB_API_TOKEN: ${{ github.token }}

